services:
  automated_information_retrieval:
    build: .
    image: automated_information_retrieval
    container_name: container_for_information_retrieval
    volumes:
      - data_volume:/app/data
    environment:
      - FOLDER_PATH=/app/data/Articles_PDF/
      - EXCEL_PATH=/app/data/Example.xlsx

volumes:
  data_volume: